spring.application.name=catalog-service


# DB connection setups 
spring.datasource.url=jdbc:postgresql://localhost:5432/catalogService
spring.datasource.username=Goku
spring.datasource.password=Goku
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
# Enables SQL optimization specifically tailored for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Show SQL queries in the console output (useful for development)
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Prefix for all endpoints 
server.servlet.context-path=/catalog

# Server Port Number
server.port=8081

# jwt secret key
jwt.secret.key=5367566859703373367639792F423F452848284D6251655468576D5A71347437 
