spring.application.name=users
# 1. Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/userService
spring.datasource.username=Goku
spring.datasource.password=Goku
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

# 3. Logging & Debugging (Optional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.servlet.context-path=/users


# 4 JWT Authentication
security.jwt.secret-key=404E635266556A586E3272357538782G413F4429472B4B6250645367566B5970
security.jwt.expiration-time=3600000

