spring.application.name=inventory

# Data Base Confifg
spring.datasource.url=jdbc:postgresql://localhost:5432/inventoryService
spring.datasource.username=Goku
spring.datasource.password=Goku
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true



# RabbitMQ Confifg
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

inventory-exchange=inventory

# Server Config 
server.servlet.context-path=/inventory
server.port=8081