spring.application.name=search

# RabbitMQ Config
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


# ELastic Search Config
spring.elasticsearch.uris: http://localhost:9200

# Server Config
server.servlet.context-path=/search
server.port=8082